export const HTAGS_LIST_REQUEST = 'HTAGS_REQUEST'
export const HTAGS_LIST_SUCESS = 'HTAGS_LIST_SUCESS'
export const HTAGS_LIST_FAILED = 'HTAGS_LIST_FAILED'

export const UPDATE_CREDIT_SUCCESS = 'UPDATE_CREDIT_SUCCESS'
export const UPDATE_CREDIT_FAILED = 'UPDATE_CREDIT_FAILED'
